skillList ={
    anatomy: {
          statRequirement:{
              min:30,
              per:30,
              spi:30,
              level:5
            },
        },
    appraise:{
          statRequirement:{
            min:20,
            perc:30,
            level:2
          }
        },
    assail:{
      statRequirement:{
        min:20,
        dex:60,
        perc:60,
        level:2
        }
      },
    arcaneMastery:{
          statRequirement:{
            str:60,
            spi:40,
            level:9
          },
          prohibited:["augment","dualWield","weaponMastery","battleTraining"],
          homeTown: ["agrabah"]
        },
    archer:{
          statRequirement:{
            str:30,
            perc:60,
            level:15
          }
        },
    armWrestle:{
          statRequirement:{
            level:1
          }
        },    
    armTrainingBasic:{
          statRequirement:{
            min:15,
            con:40,
            level:2
          }
        },
    armTrainingAdvanced:{
          statRequirement:{
            min:15,
            con:60,
            level:15
          }
        },
    armTrainingExpert:{
          statRequirement:{
            min:15,
            con:80,
            level:2
          }
        },                
    armslore:{
          statRequirement:{
            min:25,
            per:30,
            level:2
          }
        },
    augment:{
          statRequirement:{
            min:40,
            dex:10,
            spi:60,
            level:2
          },
        homeTown:["ireland"],
        // requirements:["herblore","poultice"],
        prohibited:["retreat","suckerpunch","wrestling","blindside","topple","percisionStrike","assail","dualWield","arcaneMastery","offensiveProwess","defensiveProwess","courage","valor","ironWill","weaponMastery","innateDefense","blindfighting","battleTraining"]
        },
      backstab:{
          statRequirement:{
            dex:45,
            per:30,
            level:2
          }
        },
    balance:{
          statRequirement:{
            str:20,
            dex:50,
            con:25,
            level:10
          }
        },
    bandage:{
          statRequirement:{
            level:1
          }
        },
    armslore:{
          statRequirement:{
            min:25,
            per:30,
            level:2
          }
        },
    bastion:{
      statRequirement:{
        con:62,
        dex:43,
        level:23,
        },
      prohibited:["precisionStrike","assail","evasion"],
      homeTown: "klien"
      },  
    battleTraining:{
        statRequirement:{
            str:40,
            dex:40,
            con:40,
            level:8
          },
        prohibited:["augment","fieldSurgey","assail","arcaneMastery","evasion"]
      },
    bash:{
          statRequirement:{
            str:33,
            level:2
          }
        },
    blindfighting:{
          statRequirement:{
            per:30,
            level:15
          },
          prohibited:["chant","augment"]
        },
    blindside:{
          statRequirement:{
            str:40,
            min:25,
            dex:50,
            con:60,
            per:25,
            spi:5,
            level:22
          },
        prohibited:["chant","augment"]
        },
    bowman:{
          statRequirement:{
            str:20,
            per:40,
            level:5
          }
        },
    breakDoor:{
          statRequirement:{
            str:60,
            con:25,
            level:15
          }
        },
    brew:{
          statRequirement:{
            min:25,
            spi:40,
            level:2
          },
          requirements:["herblore"],
          prohibited:["evasion"]
        },
    calm:{
          statRequirement:{
            min:35,
            spi:35,
            level:2
          }
        },
    cartography:{
          statRequirement:{
            min:20,
            per:20,
            spi:20,
            level:1
          },
          requirements:["geography"]
        },
    case:{
          statRequirement:{
            min:20,
            per:30,
            level:2
          }
        },
    chant:{
          statRequirement:{
            str:40,
            spi:20,
            level:2
          },
          prohibited:["retreat","suckerpunch","wrestling","blindside","topple","precisionStrike","assail","offensiveProwess","defensiveProwess","evasion","courage","valor","ironWill","weaponMastery","innateDefense","blindfighting"]
        },
    charge:{
          statRequirement:{
            str:40,
            dex:40,
            con:40,
            level:12
          }
        },
    choke:{
          statRequirement:{
            str:25,
            dex:35,
            per:20,
            level:2
          }
        },
    climb:{
          statRequirement:{
            str:20,
            dex:25,
            con:30,
            level:8
          }
        },
    cooking:{
          statRequirement:{
            level:1
          }
        },
    coupDeGrace:{
          statRequirement:{
            level:40
          },
          requirements:["weaponMastery"]
        },        
    courage:{
          statRequirement:{
            prime:60,
            spi:20,
            level:15
          },
          prohibited:["augment","chant"],
        },
    dash:{
          statRequirement:{
            dex:50,
            con:30,
            level:9
          }
        }, 
    deadeye:{
          statRequirement:{
            str:40,
            per:80,
            level:35
          },
          prohibited:["assail","precisionStrike","offensiveProwess","defensiveProwess","evasion"],
          requirements:["bowman","archer"]
        },                              
    deadlyPrecision:{
          statRequirement:{
            min:20,
            dex:80,
            per:80,
            level:35
          },
          requirements:["precisionStrike"]
        },   
    disguise:{
          statRequirement:{
            min:25,
            dex:25,
            per:60,
            level:5
          }
        },
    dodge:{
          statRequirement:{
            dex:40,
            per:25,
            level:2
          }
        },
    draw:{
          statRequirement:{
            dex:40,
            level:2
          }
        },
    dressWound:{
          statRequirement:{
            mind:45,
            per:25,
            spi:45,
            level:10
          }
        },
    dualWield:{
        statRequirement:{  
          con:30,
          str:30,
          dex:40,
          level:17
        },
        prohibited:["augment","fieldSurgery","arcaneMastery"]
      },
    elbow:{
        statRequirement:{  
          str:50,
          dex:25,
          con:30,
          per:20,
          level:2
        },
      },
                      
    entrance:{
        statRequirement:{ 
          min:50,
          per:30,
          spi:50,
          level:5 
        },
        requirements:["play"],
        homeTown:["lima","london","sanfran"]
      },           
    evasion:{
        statRequirement:{ 
          min:20,
          dex:60,
          perc:60,
          level:10 
        },
        requirements:["sneak","hide","dodge"],
        prohibited:["bash","brew","chant","headbutt","warcry","sharpshooter","sniper","archer","deadeye","runelore","topple","innateDefense","battleTraining","pistolWhip","bastion"],
      },             
    feint:{
        statRequirement:{  
          min:30,
          dex:40,
          per:30,
          level:20
        },
      },
                      
    fieldSurgery:{
        statRequirement:{  
          min:50,
          dex:20,
          per:30,
          spi:50,
          level:20
        },
        requirements:["anatomy","firstAid","dressWound"],
        prohibited:["precisionStrike","assail","dualWield","offensiveProwess","defensiveProwess","battleTraining"],
        homeTown:["lima","london","sanfran"]
      },
                      
    firstAid:{
        statRequirement:{  
          min:35,
          per:25,
          spi:35,
          level:2
        },
        requirements:["bandage"],
        homeTown:["lima","london","sanfran"]
      },
                      
    fishing:{
        statRequirement:{ 
          level:1 
        },
      },
                      
    fistFighting:{
        statRequirement:{
          str:40,
          con:40,
          dex:40,
          per:20  
        },
      },
                      
    flashingBlades:{
        statRequirement:{  
          min:20,
          dex:80,
          per:80,
          level:33
        },
        requirements:["precisionStrike","weaponMastery"],
      },
                      
    flavor:{
        statRequirement:{  
          min:25,
          spi:45,
          level:1
        },
        requirements:["herblore"],
        homeTown:["lima","ireland"]
      },
                      
    fletching:{
        statRequirement:{  
          str:10,
          min:20,
          dex:40,
          per:30,
          level:10
          },
      },
                      
    forage:{
        statRequirement:{  
        level:8
        },
      },
                      
    geography:{
        statRequirement:{
          min:20,
          per:20,
          spi:20,
          level:5  
        },
      },
                      
    gunplay:{
        statRequirement:{  
          per:25,
          level:2
        },
        homeTown:["lima","london","sanfran"]
      },
                      
    haggle:{
        statRequirement:{  
          level:2
        },
      },
                      
    headbutt:{
        statRequirement:{  
          con:33,
          level: 2
        },
        prohibited:["assail","evasion"]
      },
    herblore:{
        statRequirement:{
            min:30,
            spi:35,
            level:2
          },
        homeTown:["ireland", "lima","klien","agrabah"] 
      },                     
    heroicRescue:{
        statRequirement:{  
          str:30,
          dex:30,
          con:40,
          level:12
        },
        requirements:["rescue"],
      },
                      
    hide:{
        statRequirement:{
          dex:40,
          perc:40,
          level: 2  
        },
      },
                      
    hunt:{
        statRequirement:{
          min:20,
          dex:20,
          con:20,
          per:30,
          level:5 
        },
      },
                      
    innateDefense:{
        statRequirement:{  
          str:65,
          dex:65,
          con:65,
          level:8
        },
        prohibited:["chant","augment","precisionStrike","assail","evasion"]
      },              
    inspire:{
        statRequirement:{  
          min:35,
          spi:35,
          level: 2
        },
        homeTown:["lima"]
      },                
    ironWill:{
        statRequirement:{  
          prime:90,
          spi:30
        },
        requirements:["valor"],
        prohibited:["chant","augment"]
      },                
    judge:{
        statRequirement:{
          per:30,
          level:2 
        },
      },                
    juggling:{
        statRequirement:{  
          dex:55,
          level:2
        },
      },              
    kick:{
        statRequirement:{  
          dex:33,
          level:2
        },
      },                
    listen:{
        statRequirement:{  
          per:40,
          level: 2
        },
      },                
    lullaby:{
        statRequirement:{
          min:45,
          spi:60,
          level:35 
        },
        requirements:["sing"],
        homeTown:["london","lima","sanfran"]
      },
                    
    makeAmulet:{
        statRequirement:{  
          min:25,
          dex:20,
          spi:40,
          level: 2
        },
        requirements:["herblore"],
      },              
    makeBandage:{
        statRequirement:{  
        min:20,
        dex:20,
        spi:35,
        level: 2
        },
      },                
    makeOil:{
        statRequirement:{  
          min:25,
          spi:45,
          level:5
        },
        requirements:["herblore"],
      },               
    makeStaff:{
        statRequirement:{  
          min:20,
          dex:20,
          spi:50,
          level:5
        },
        requirements:["herblore"]
      },
                      
    markTarget:{
        statRequirement:{  
          min:20,
          dex:60,
          per:60,
          level: 15
        },
        requirements:["hide","case"],
        },               
    marksman:{
        statRequirement:{  
          per:40,
          level:5
        },
        requirements:["gunplay"],
      },
                      
    meditate:{
        statRequirement:{  
          min:55,
          con:25,
          spi:43,
          level:5
        },
      },
                      
    mending:{
        statRequirement:{  
        level: 2
        },
      },               
    mixPotion:{
        statRequirement:{  
          min:40,
          spi:60,
          level:20
        },
        requirements:["herblore","brew"],
        homeTown:["irlend"]
      },
                      
    nightVision:{
        statRequirement:{  
          min:20,
          con:20,
          per:60,
          level:15
        },
      },
                      
    parry:{
        statRequirement:{  
          min:25,
          dex:40,
          per:10,
          level:10
        },
      },
    parryadvanced:{
        statRequirement:{  
          min:25,
          dex:60,
          per:15,
          level:20
        },
      },
    parryExpert:{
        statRequirement:{  
          min:25,
          dex:80,
          per:20,
          level:30
        },
      },               
    peek:{
        statRequirement:{  
          min:20,
          dex:30,
          per:50,
          level:11
        },
      },
                                     
    pickLock:{
        statRequirement:{  
          min:20,
          dex:40,
          level:2
        }
      },
                      
    pistolWhip:{
        statRequirement:{  
          str:30,
          dex:40,
          per:40,
          level:10
        },
        prohibited:["assail","evasion"]
      },
                      
    play:{
        statRequirement:{  
        level:1
        },
      },
                      
    poisoning:{
        statRequirement:{  
            min:30,
            per:30,
            spi:30,
            level: 5
        },
      },
                      
    poultice:{
        statRequirement:{  
          min:25,
          spi:40,
          level:2
        },
        requirements:["bandage","herblore"],
        homeTown:["ireland","lima"]
      },
                      
    powder:{
        statRequirement:{  
          min:25,
          spi:45,
          level:5
        },
        requirements:["herblore","brew"],
        homeTown:["ireland"]
      },
                      
    praise:{
        statRequirement:{  
          min:30,
          per:30,
          level:2
        },
      },
                      
    precisionStrike:{
        statRequirement:{  
         min:25,
         dex:70,
         per:70,
         level:25
        },
        requirements:["assail"]
      },
                      
    purify:{
        statRequirement:{  
          min:25,
          spi:45,
          level:5
        },
        requirements:["herblore"],
      },
    quickdraw:{
        statRequirement:{  
          dex:30,
          per:60,
          level:35
        },
        requirements:["sharpshooter"],
      },
                      
    rage:{
        statRequirement:{  
          str:40,
          dex:20,
          con:40,
          level:12
        },
      },
                      
    rally:{
        statRequirement:{  
          str:30,
          dex:30,
          con:30,
          level:32
        },
      },
                      
    repair:{
        statRequirement:{  
          level:2
        },
      },
                      
    rescue:{
        statRequirement:{  
          str:20,
          dex:20,
          con:30,
          level:6
        },
      },
                      
    retreat:{
        statRequirement:{  
          min:20,
          dex:40,
          per:40,
          level:25
        },
        prohibited:["augment","chant"],
      },
                      
    ride:{
        statRequirement:{  
         str:20,
         min:20,
         dex:30,
         con:30,
         level:7
        },
      },
                      
    riposte:{
        statRequirement:{  
          min:25,
          dex:40,
          per:10,
          level:15
        },
        requirements:["parry"],
      },
                      
    root:{
        statRequirement:{  
          min:30,
          con:30,
          spi:55,
          level:10
        },
        requirements:["herblore","brew","poultice"],
        homeTown:["irlend"]
        },
                      
    satire:{
        statRequirement:{  
          min:30,
          per:30,
          level:2
        },
      },
                      
    scan:{
        statRequirement:{  
          per:35,
          level:2
        },
      },
                      
    sharpshooter:{
        statRequirement:{  
          per:60,
          level:15
        },
        requirements:["gunplay","marksman"],
        prohibited:["precisionStrike","assail","evasion"],
        homeTown:["london","sanfran"]
      },
    shipbuilding:{
        statRequirement:{  
          min:30,
          dex:25,
          con:25,
          level:2
        },
      },
                  
    sing:{
        statRequirement:{  
          min:45,
          per:15,
          spi:50,
        },
      },
                      
    sneak:{
        statRequirement:{  
          dex:50,
          con:20,
          level:2
        },
      },
                      
    sniper:{
        statRequirement:{  
          per:80,
          level:35
        },
        requirements:["gunplay","marksman","sharpshooter"],
        prohibited:["precisionStrike","assail","evasion"],
        homeTown:["london","sanfran"]
      },
    steal:{
      statRequirements:{
        min:20,
        dex:20,
        per:20,
        level:2
        }
      },
    suckerpunch:{
      statRequirements:{
        min:20,
        dex:40,
        con:40,
        str:40,
        per:25,
        level:2
        },
      prohibited:["chant","augment"]
      },
    sustainedBreath:{
      statRequirements:{
        dex:20,
        con:45,
        str:25,
        level:2
        }
      },
    swim:{
          statRequirement:{
            str:20,
            dex:20,
            con:30,
            level:2
          }
        },
    swordsmanshipBasic :{
          statRequirement:{
            str:40,
            min:15,
            level:2
          }
        },
    swordsmanshipAdvanced :{
          statRequirement:{
            str:60,
            min:20,
            level:15
          }
        },
    swordsmanshipExpert :{
          statRequirement:{
            str:80,
            min:25,
            level:30
          }
        },
    tailor:{
          statRequirement:{
            str:20,
            dex:35,
            level:2
          }
        },
    tannery:{
          statRequirement:{
            level:2
          }
        },
    throw:{
          statRequirement:{
            str:25,
            dex:30,
            con:25,
            level:3
          }
        },
    topple:{
          statRequirement:{
            str:40,
            min:20,
            dex:72,
            con:40,
            spi:5,
            level:25
          },
        prohibited:["chant","augment","assail","evasion"],
        },
    trapping:{
          statRequirement:{
            min:25,
            dex:40,
            per:60,
            level:16
          }
        },
  
    triage:{
          statRequirement:{
            min:50,
            dex:20,
            per:30,
            spi:50,
            level:2
          },
          requirements:["anatonmy","firstAid","dressWound","fieldSurgery"],
        },
    tumble:{
          statRequirement:{
            dex:60,
            per:30,
            level:2
          }
        },
    twogun:{
          statRequirement:{
            str:30,
            dex:40,
            per:60,
            level:25
          },
        requirements:["gunplay"],
        homeTown:["sanfran"]
        },  
    valor:{
          statRequirement:{
            prime:85,
            spi:25,
            level:25
          },
          requirements:["courage"],
        },
    vanish:{
          statRequirement:{
            dex:80,
            per:80,
            level:25
          },
        requirements:["sneak","hide","evasion"],
        },
    warcry:{
          statRequirement:{
            str:30,
            dex:10,
            con:50,
            per:20,
            level:5
          },
          prohibited:["assail","evasion"]
        },
    weaponMastery:{
          statRequirement:{
            prime:80,
            level:25
          },
        prohibited:["chant","augment","arcaneMastery"]
        },
    wrestling:{
          statRequirement:{
            str:60,
            dex:40,
            con:60,
            perc:25,
            spi:5,
            level:25
          },
        prohibited:["chant","augment"]
        }, 
    fencingBasic: {
      statRequirement:{
        dex: 40,
        min: 15,
        level: 2
        },      
      },
    fencingAdvanced: {
      statRequirement:{
        dex: 40,
        min: 20,
        level: 15
        },      
      },
    fencingExpert: {
      statRequirement:{
        dex: 40,
        min: 25,
        level: 30
        },      
      },
  
    }
  
  module.exports = {
  skillList
  }
  